### ISSUE TITLE
Modification for OpenSUSE leap kernel

### ISSUE THREAD

**Issue by zarath** [smlinux/rtl8723de#10]
https://github.com/smlinux/rtl8723de/blob/cc4a9f6b93dffa2a81d94ff8edc858df73eec2bb/hal/rtl8723d/pci/pci_ops_linux.c#L925

It's not an issue but the wifi driver api of openSUSE's leap 4.4.x-Kernel series is vanilla 4.7.x.

Changing the numbers in this line to 4,4,0 enables compilation and usage with openSUSE leap.

As I didn't find a SUSE specific macro to detect their kernels source, I've created an opensuse branch in my fork

**Comment by smlinux** [comment]
Changes have been added to the 4.10-down branch.
