### ISSUE TITLE
Wireless Networks not detected despite installing latest drivers

### ISSUE THREAD

**Issue by rembranded** [smlinux/rtl8723de#24]
Hi, I have a HP Laptop (Model: HP 15q-BU010TU) that I purchased recently and it came with FreeDOS. I proceeded to install the latest Ubuntu off a USB stick and the installation went just fine. I was connected via a wired ethernet connection at the time. Post installation, I was able to go about my work when I realised that the Wi-Fi wasn't working. I did some searching online and installed the latest version of the rtl8732de drivers from Larry W. Fingers github. Now my system is able to detect that I have wireless capability, but when I click on 'Search for networks' it's spinning forever and none of the network SSIDs appear. I've checked my network setup also and my SSID is hidden and another laptop is able to connect to the same SSID, so it isn't a network issue. Can anyone please help?

**Comment by AvirahJ** [comment]
May be using ant_sel=2 module option along with rtl8723de module can work? Explained here:
https://h30434.www3.hp.com/t5/Notebook-Wireless-and-Networking/Realtek-8723DE-wifi-module-amp-Bluetooth-Linux-driver/m-p/6477307/highlight/true#M146067
