### ISSUE TITLE
WiFi not being recognized

### ISSUE THREAD

**Issue by ayanbanrj** [smlinux/rtl8723de#3]
I just downloaded the ZIP of the repo (branch 4.11-up) and ran:
```
make
sudo make install
```
No errors are thrown but the WiFi card is still not recognized. I am running 32-bit Linux Mint 18.3 with manually upgraded kernel, version 4.14.0-041400-generic.

Any suggestions?

**Comment by smlinux** [comment]
Add the module to startup and restart the PC:
```
sudo su
echo 8723de >> /etc/modules
reboot
```

**Comment by ayanbanrj** [comment]
@smlinux You are great!!! :+1: :+1: :+1:
