### ISSUE TITLE
Arch ERROR IN /home/....../rtl8723de/core/rtw_debug.o

### ISSUE THREAD

**Issue by IVAN-DPP** [smlinux/rtl8723de#62]
Good night, i have a problem with this, my linux is Arch with kernel 5.4.13-arch1-1, thank's

make[2]: *** [scripts/Makefile.build:266: /home/.../rtl8723de/core/rtw_debug.o] Error 1
make[1]: *** [Makefile:1652: /home/.../rtl8723de] Error 2
make[1]: se sale del directorio '/usr/lib/modules/5.4.13-arch1-1/build'
make: *** [Makefile:1885: modules] Error 2

**Comment by ghost** [comment]
This repository driver files aren't the most updated.

The driver file from Realtek FTP Server (below link) is the newest:
https://github.com/alanfox2000/realtek-linux/raw/master/RTL8723DE/20190917_RTL8723DE_WiFi_linux_v5.7.7_33046_COEX20181130-2e2e.20190917.zip

**Comment by IVAN-DPP** [comment]
> This repository driver files aren't the most updated.
> 
> The driver file from Realtek FTP Server (below link) is the newest:
> https://github.com/alanfox2000/realtek-linux/raw/master/RTL8723DE/20190917_RTL8723DE_WiFi_linux_v5.7.7_33046_COEX20181130-2e2e.20190917.zip

No, I'm sorry, don't work, is the same problem, I think that is the kernel of Arch, but I have installed all kernel packs.

**Comment by IVAN-DPP** [comment]
Ok, I upgrade the linux vanilla kernel 5.4.13, and install pacman -S ncurses make gcc bc openssl [1], and finally install without problem, but!!!! when I rebooted the computer, the kernel panics and don't charge the system.

[1] https://linuxhint.com/upgrade-kernel-on-arch-linux/

**Comment by IVAN-DPP** [comment]
> Ok, I upgrade the linux vanilla kernel 5.4.13, and install pacman -S ncurses make gcc bc openssl [1], and finally install without problem, but!!!! when I rebooted the computer, the kernel panics and don't charge the system.
> 
> [1] https://linuxhint.com/upgrade-kernel-on-arch-linux/

The next step is, I change the kernel for LTS, and install this repo of this link https://h30434.www3.hp.com/t5/Notebook-Wireless-and-Networking/Realtek-8723DE-wifi-module-amp-Bluetooth-Linux-driver/td-p/6477307, and all fine.
