### ISSUE TITLE
Please close this repo

### ISSUE THREAD

**Issue by vitaliy-kuzmich** [smlinux/rtl8723de#66]
Hello, code in this repo broke down the whole system, please remove it. Or mark as out of date.

**Comment by andrescanm** [comment]
Yes! Confirmed, I tried several distributions and in all the same problem arises, when restarting the laptop everything goes to hell.

**Comment by vitaliy-kuzmich** [comment]
Here it is working one : https://github.com/lwfinger/rtlwifi_new

**Comment by codejack-CR** [comment]
> Hello, code in this repo broke down the whole system, please remove it. Or mark as out of date.

On Linux Kernel 5.5, the startup messages show linux kernel panic. This repo is dangerous for anyone trying to use kernel version > 5.3.

**Comment by mikhailnov** [comment]
What is the problem exactly?

**Comment by codejack-CR** [comment]
> What is the problem exactly?

I don't have the exact log but, I remember the error messages being that the installed version of the driver differs from the kernel version and that it failed to load for that reason. You can test it on a separate partitioned OS if you have the same wifi module.

**Comment by mikhailnov** [comment]
> that the installed version of the driver differs from the kernel version and that it failed to load for that reason

My patch https://github.com/smlinux/rtl8723de/pull/67 fixes it

**Comment by ghost** [comment]
This driver is perfect on xubuntu 19.04 which using the kernel version 5.0.

**Comment by adrianperal** [comment]
today i updated manjaro to 20.0 with lts kernel 5.4, went smooth, no problem at all, everything working as it should. RTL8723de

**Comment by inpos** [comment]
DON'T close this repo. Only this driver is magically working. Driver from "rtlwifi_new" repo drop me to hell.
Thank you for this repo.

**Comment by vitaliy-kuzmich** [comment]
okay, some confirmations that it works
