### ISSUE TITLE
Build fails on new lnux kernel 5.7.2

### ISSUE THREAD

**Issue by pcoder59** [smlinux/rtl8723de#71]
I had previously posted issue on linux kernel 5.6.15 and was fixed. Now the newer kernel 5.7.2 has the same issue of build failing on arch linux.

[make.log](https://github.com/smlinux/rtl8723de/files/4785616/make.log)

**Comment by smlinux** [comment]
Try with this commit: 7b7fc22beaa54d3a0676da345e8a1ac943557463

**Comment by pcoder59** [comment]
Yes, Built successfully on kernel ver.5.7.2

This issue was there for kernel ver.5.6.15 when I tried rolling back my kernel yesterday. I haven't tried building on the older linux kernel.
